import React from 'react';
import { Cpu, Mail, Sparkles, User, Info, Clock, LogOut, History, Palette, Volume2 } from 'lucide-react';
import { CommandSuggestion } from './types';

export const suggestions: CommandSuggestion[] = [
  { command: 'whoami', description: 'Display identity', icon: <User className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'man dmytro', description: 'Manual page', icon: <Info className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'skills', description: 'View technical expertise', icon: <Cpu className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'history', description: 'View career timeline', icon: <History className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'contact', description: 'Get contact information', icon: <Mail className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'uptime', description: 'Session uptime', icon: <Clock className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'theme', description: 'Switch color theme', icon: <Palette className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'sound', description: 'Toggle terminal sounds', icon: <Volume2 className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'clear', description: 'Clear terminal screen', icon: <Sparkles className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'exit', description: 'Terminate the current session', icon: <LogOut className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
];

export const commands: Record<string, string[]> = {
  skills: [
    'Programming Languages:',
    '  Java    ████████████ expert',
    '  Kotlin  ████████████ expert',
    '  Scala   ████████░░░░ proficient',
    '  Python  ██████░░░░░░ familiar',
    '',
    'System Design:',
    '  Microservices      ████████████ expert',
    '  Event-driven arch  ████████████ expert',
    '  API design         ████████████ expert',
    '',
    'Core Technologies:',
    '  Spring Boot        ████████████ expert',
    '  Project Reactor    ████████░░░░ proficient',
    '  Apache Kafka       ████████████ expert',
    '  Elasticsearch      ████████░░░░ proficient',
    '  Postgres/MySQL     ████████░░░░ proficient',
  ],
  skillsMobile: [
    'Languages:',
    '  Java    ██████ expert',
    '  Kotlin  ██████ expert',
    '  Scala   ████░░ proficient',
    '  Python  ███░░░ familiar',
    '',
    'System Design:',
    '  Microservices  ██████ expert',
    '  Event-driven   ██████ expert',
    '  API design     ██████ expert',
    '',
    'Core Tech:',
    '  Spring Boot  ██████ expert',
    '  Reactor      ████░░ proficient',
    '  Kafka        ██████ expert',
    '  Elastic      ████░░ proficient',
    '  Postgres     ████░░ proficient',
  ],
  contact: [
    '<a href="https://github.com/dkoval" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;" class="inline-flex items-center hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>github.com/dkoval</a>',
    '<a href="https://linkedin.com/in/dmytrokoval" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;" class="inline-flex items-center hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>linkedin.com/in/dmytrokoval</a>',
    '<a href="https://twitter.com/dkovalbuzz" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;" class="inline-flex items-center hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>twitter.com/dkovalbuzz</a>',
    '<a href="mailto:dkoderinc@gmail.com" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;" class="inline-flex items-center hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>dkoderinc@gmail.com</a>',
  ],
  whoami: [
    'Dmytro Koval',
    '────────────',
    'Focus:      Backend & Distributed Systems',
    'Approach:   Managing complexity through modular, decoupled design',
    'Heuristic:  First Principles + Battle-Hardened Experience + AI-Acceleration',
    'Delivery:   Distilling vague requirements into production-grade reality',
    'Standard:   Engineering for failure to ensure predictable system recovery',
  ],
  whoamiDesktop: [
    '  ██████╗ ██╗  ██╗',
    '  ██╔══██╗██║ ██╔╝',
    '  ██║  ██║█████╔╝',
    '  ██║  ██║██╔═██╗',
    '  ██████╔╝██║  ██╗',
    '  ╚═════╝ ╚═╝  ╚═╝',
    '',
    '  Dmytro Koval',
    '  ────────────',
    '  Focus:      Backend & Distributed Systems',
    '  Approach:   Managing complexity through modular, decoupled design',
    '  Heuristic:  First Principles + Battle-Hardened Experience + AI-Acceleration',
    '  Delivery:   Distilling vague requirements into production-grade reality',
    '  Standard:   Engineering for failure to ensure predictable system recovery',
  ],
  history: [
    ' 1  Started professional software development',
    ' 2  First enterprise Java project \u2014 hooked on the JVM',
    ' 3  Adopted microservices architecture early',
    ' 4  Deep dive into Kafka & event-driven systems',
    ' 5  Tried Kotlin for backend \u2014 loved it',
    ' 6  Architecting distributed systems at scale',
    ' 7  Pushing backend engineering forward',
    ' 8  Building with OSS and AI',
    ' 9  Still shipping. Still learning.',
  ],
  'man dmytro': [
    '<span style="color: var(--terminal-gray)">DMYTRO(1)                    User Commands                    DMYTRO(1)</span>',
    '',
    '<span style="color: var(--terminal-primary)">NAME</span>',
    '       dmytro - a software engineer who builds things that scale',
    '',
    '<span style="color: var(--terminal-primary)">SYNOPSIS</span>',
    '       dmytro [--backend] [--distributed] [--java|--kotlin] [problem...]',
    '',
    '<span style="color: var(--terminal-primary)">DESCRIPTION</span>',
    '       Dmytro Koval is a Senior Software Engineer with 15+ years of',
    '       experience building robust, scalable, and efficient server-side',
    '       applications. Specializes in microservices, event-driven',
    '       architecture, and high-performance distributed systems.',
    '',
    '<span style="color: var(--terminal-primary)">OPTIONS</span>',
    '       --backend          Preferred mode of operation',
    '       --distributed      Excels in this environment',
    '       --mentoring        Also available',
    '',
    '<span style="color: var(--terminal-primary)">BUGS</span>',
    '       None known. Reports welcome at: dkoderinc@gmail.com',
    '',
    '<span style="color: var(--terminal-primary)">SEE ALSO</span>',
    '       skills(1), history(1), contact(1)',
    '',
    '<span style="color: var(--terminal-gray)">DKODER INC.                       2026                       DMYTRO(1)</span>',
  ],
};
