import React from 'react';
import { Cpu, Mail, Sparkles, User, Info, FolderOpen, Clock } from 'lucide-react';
import { CommandSuggestion } from './types';

export const suggestions: CommandSuggestion[] = [
  { command: 'whoami', description: 'Who am I?', icon: <User className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'man dmytro', description: 'Manual page', icon: <Info className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'skills', description: 'View technical expertise', icon: <Cpu className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'projects', description: 'GitHub projects', icon: <FolderOpen className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'contact', description: 'Get contact information', icon: <Mail className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'uptime', description: 'Session uptime', icon: <Clock className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'uname -a', description: 'System info', icon: <Info className="w-4 h-4 text-[#00FF41]" /> },
  { command: 'clear', description: 'Clear terminal screen', icon: <Sparkles className="w-4 h-4 text-[#00FF41]" /> },
];

export const commands: Record<string, string[]> = {
  help: [
    'Available commands:',
  ],
  _helpFooter: [
    '',
    'Tips:',
    '  • Use ↑↓ arrows to navigate command history',
    '  • Tab for autocomplete',
    '  • Ctrl+L to clear',
  ],
  skills: [
    'Programming Languages:',
    '  Java    ████████████ expert',
    '  Kotlin  ████████████ expert',
    '  Scala   ████████░░░░ proficient',
    '  Python  ██████░░░░░░ familiar',
    '',
    'System Design:',
    '  Microservices      ████████████ expert',
    '  Event-driven arch  ████████████ expert',
    '  API design         ████████████ expert',
    '',
    'Core Technologies:',
    '  Spring Boot        ████████████ expert',
    '  Project Reactor    ████████░░░░ proficient',
    '  Apache Kafka       ████████████ expert',
    '  Elasticsearch      ████████░░░░ proficient',
    '  Postgres/MySQL     ████████░░░░ proficient',
  ],
  contact: [
    '<a href="https://github.com/dkoval" target="_blank" rel="noopener noreferrer" class="inline-flex items-center text-[#00FF41] hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>github.com/dkoval</a>',
    '<a href="https://linkedin.com/in/dmytrokoval" target="_blank" rel="noopener noreferrer" class="inline-flex items-center text-[#00FF41] hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>linkedin.com/in/dmytrokoval</a>',
    '<a href="https://twitter.com/dkovalbuzz" target="_blank" rel="noopener noreferrer" class="inline-flex items-center text-[#00FF41] hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>twitter.com/dkovalbuzz</a>',
    '<a href="mailto:dkoderinc@gmail.com" target="_blank" rel="noopener noreferrer" class="inline-flex items-center text-[#00FF41] hover:underline"><svg class="w-4 h-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>dkoderinc@gmail.com</a>',
  ],
  whoami: [
    'dkoval:x:1000:1000:Dmytro Koval,,,:/home/dkoval:/bin/bash',
  ],
  'uname -a': [
    'Linux dkoderinc 6.1.0-backend #1 SMP PREEMPT Tue Jan 1 00:00:00 UTC 2026 x86_64 GNU/Linux',
  ],
  'man dmytro': [
    'DMYTRO(1)                    User Commands                    DMYTRO(1)',
    '',
    'NAME',
    '       dmytro - a software engineer who builds things that scale',
    '',
    'SYNOPSIS',
    '       dmytro [--backend] [--distributed] [--java|--kotlin] [problem...]',
    '',
    'DESCRIPTION',
    '       Dmytro Koval is a Senior Software Engineer with 15+ years of',
    '       experience building robust, scalable, and efficient server-side',
    '       applications. Specializes in microservices, event-driven',
    '       architecture, and high-performance distributed systems.',
    '',
    'OPTIONS',
    '       --backend          Preferred mode of operation',
    '       --distributed      Excels in this environment',
    '       --mentoring        Also available',
    '',
    'BUGS',
    '       None known. Reports welcome at: dkoderinc@gmail.com',
    '',
    'SEE ALSO',
    '       skills(1), projects(1), contact(1)',
    '',
    'DKODER INC.                       2026                       DMYTRO(1)',
  ],
  projects: [
    'GitHub Projects:',
    '',
    '  See pinned repositories and contributions at:',
    '  <a href="https://github.com/dkoval" target="_blank" rel="noopener noreferrer" class="text-[#00FF41] hover:underline">https://github.com/dkoval</a>',
  ],
};
