import React from 'react';
import { Cpu, Mail, Sparkles, User, Info, Clock, LogOut, History, Palette } from 'lucide-react';
import { CommandSuggestion } from './types';

export const suggestions: CommandSuggestion[] = [
  { command: 'whoami', description: 'Display identity', icon: <User className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'man dmytro', description: 'Manual page', icon: <Info className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'skills', description: 'View technical expertise', icon: <Cpu className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'history', description: 'View career timeline', icon: <History className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'contact', description: 'Get contact information', icon: <Mail className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'uptime', description: 'Session uptime', icon: <Clock className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'theme', description: 'Switch color theme', icon: <Palette className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'clear', description: 'Clear terminal screen', icon: <Sparkles className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
  { command: 'exit', description: 'Terminate the current session', icon: <LogOut className="w-4 h-4" style={{ color: 'var(--terminal-primary)' }} /> },
];

export const commands: Record<string, string[]> = {
  help: [
    'Available commands:',
  ],
  _helpFooter: [
    '',
    'Tips:',
    '  • Use ↑↓ arrows to navigate command history',
    '  • Tab for autocomplete',
    '  • Ctrl+L to clear',
  ],
  skills: [
    'Programming Languages:',
    '  Java    ████████████ expert',
    '  Kotlin  ████████████ expert',
    '  Scala   ████████░░░░ proficient',
    '  Python  ██████░░░░░░ familiar',
    '',
    'System Design:',
    '  Microservices      ████████████ expert',
    '  Event-driven arch  ████████████ expert',
    '  API design         ████████████ expert',
    '',
    'Core Technologies:',
    '  Spring Boot        ████████████ expert',
    '  Project Reactor    ████████░░░░ proficient',
    '  Apache Kafka       ████████████ expert',
    '  Elasticsearch      ████████░░░░ proficient',
    '  Postgres/MySQL     ████████░░░░ proficient',
  ],
  contact: [
    '╭─ Contact ─────────────────────────────╮',
    '│                                       │',
    '<a href="https://github.com/dkoval" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;">│  ◆  github.com/dkoval                  │</a>',
    '<a href="https://linkedin.com/in/dmytrokoval" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;">│  ◆  linkedin.com/in/dmytrokoval        │</a>',
    '<a href="https://twitter.com/dkovalbuzz" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;">│  ◆  twitter.com/dkovalbuzz             │</a>',
    '<a href="mailto:dkoderinc@gmail.com" target="_blank" rel="noopener noreferrer" style="color: var(--terminal-primary); text-decoration: none;">│  ✉  dkoderinc@gmail.com                │</a>',
    '│                                       │',
    '╰───────────────────────────────────────╯',
  ],
  whoami: [
    'Dmytro Koval',
    '─────────────────────────────',
    'Focus: Backend & Distributed Systems',
  ],
  whoamiDesktop: [
    '  ██████╗ ██╗  ██╗      Dmytro Koval',
    '  ██╔══██╗██║ ██╔╝      ─────────────────────────────',
    '  ██║  ██║█████╔╝       Focus: Backend & Distributed Systems',
    '  ██║  ██║██╔═██╗',
    '  ██████╔╝██║  ██╗',
    '  ╚═════╝ ╚═╝  ╚═╝',
  ],
  history: [
    '    1  Started professional software development',
    '    2  First enterprise Java project \u2014 fell in love with the JVM',
    '    3  Adopted microservices architecture early',
    '    4  Deep dive into Apache Kafka & event-driven systems',
    '    5  Tried Kotlin for backend development \u2014 absolutely loved it',
    '    6  Architecting distributed systems at scale',
    '    7  Pushing backend engineering initiatives forward',
    '    8  Building with OSS and AI',
    '    9  Still shipping. Still learning.',
  ],
  'man dmytro': [
    '<span style="color: var(--terminal-gray)">DMYTRO(1)                    User Commands                    DMYTRO(1)</span>',
    '',
    '<span style="color: var(--terminal-primary)">NAME</span>',
    '<span style="color: var(--terminal-gray)">       dmytro - a software engineer who builds things that scale</span>',
    '',
    '<span style="color: var(--terminal-primary)">SYNOPSIS</span>',
    '<span style="color: var(--terminal-gray)">       dmytro [--backend] [--distributed] [--java|--kotlin] [problem...]</span>',
    '',
    '<span style="color: var(--terminal-primary)">DESCRIPTION</span>',
    '<span style="color: var(--terminal-gray)">       Dmytro Koval is a Senior Software Engineer with 15+ years of</span>',
    '<span style="color: var(--terminal-gray)">       experience building robust, scalable, and efficient server-side</span>',
    '<span style="color: var(--terminal-gray)">       applications. Specializes in microservices, event-driven</span>',
    '<span style="color: var(--terminal-gray)">       architecture, and high-performance distributed systems.</span>',
    '',
    '<span style="color: var(--terminal-primary)">OPTIONS</span>',
    '<span style="color: var(--terminal-gray)">       --backend          Preferred mode of operation</span>',
    '<span style="color: var(--terminal-gray)">       --distributed      Excels in this environment</span>',
    '<span style="color: var(--terminal-gray)">       --mentoring        Also available</span>',
    '',
    '<span style="color: var(--terminal-primary)">BUGS</span>',
    '<span style="color: var(--terminal-gray)">       None known. Reports welcome at: dkoderinc@gmail.com</span>',
    '',
    '<span style="color: var(--terminal-primary)">SEE ALSO</span>',
    '<span style="color: var(--terminal-gray)">       skills(1), history(1), contact(1)</span>',
    '',
    '<span style="color: var(--terminal-gray)">DKODER INC.                       2026                       DMYTRO(1)</span>',
  ],
};
